// THIS FILE IS GENERATED BY FLUTTERFIRE CLI
// Run: flutterfire configure
// Do NOT commit your real API keys to version control.
//
// Steps:
// 1. Install FlutterFire CLI:  dart pub global activate flutterfire_cli
// 2. Login to Firebase:        firebase login
// 3. Run in project root:      flutterfire configure
// 4. Select your Firebase project (or create one)
// 5. This file will be auto-generated with your real config values.
//
// Until then, this placeholder prevents compile errors.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️  REPLACE THESE WITH YOUR REAL VALUES after running: flutterfire configure

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ9cber0mSrs58P6L9IlAkFQze1ulrYOY',
    appId: '1:245627860959:android:64d23d81c2f054b862366a',
    messagingSenderId: '245627860959',
    projectId: 'invoice-app-55978',
    storageBucket: 'invoice-app-55978.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.example.invoiceApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
  );
}
